# Generated by Django 4.0.4 on 2022-05-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('cpf', models.CharField(default=None, max_length=11)),
                ('nasc', models.CharField(default=None, max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('fone', models.CharField(blank=True, max_length=15, null=True)),
                ('assinatura_FK', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.assinatura')),
                ('idUser_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=main.models.upload_imagem_filme)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=main.models.upload_imagem_banner)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=main.models.upload_imagem_logo)),
                ('descricao', models.CharField(default=None, max_length=500)),
                ('ano', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('temps', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('categoria_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filmes')),
                ('usuario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios')),
            ],
        ),
    ]
