# Generated by Django 4.0.4 on 2022-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='temps',
        ),
    ]
